### ISSUE TITLE
Feature: implement `toString` for `PutMessageAdapter` and `AckMessageAdapter`

### ISSUE THREAD

**Issue by 678098** [bloomberg/blazingmq-sdk-java#14]
### Is there an existing proposal for this?

- [X] I have searched the existing proposals

### Is your feature request related to a problem?

From the logs you can see that `toString` is implemented to `PushMessageAdapter` only.
```
12:27:06,590 (main) ERROR SessionStressIT:267 Last PUT : com.bloomberg.bmq.Session$QueueAdapter$PutMessageAdapter@6b05a1fd
12:27:06,590 (main) ERROR SessionStressIT:268 Last ACK : com.bloomberg.bmq.Session$QueueAdapter$AckMessageAdapter@45ac5ad1
12:27:06,592 (main) ERROR SessionStressIT:269 Last PUSH: [ Queue URI: bmq://bmq.test.mmap.priority/java-it-cbc42d86-7c43-4f7c-8377-be88b7a06108 ][ PushHeader [ Flags=2 MessageWords=267 OptionsWords=2 CompressionType=0 HeaderWords=8 QueueId=0 MessageGUID=0003E7000002F90E62391B26CF840BF9 SchemaWireId=1 ] ][ PushMessage [ SubQueueIds [ [0] ] ][ Payload ["................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................***" ][ MessageProperties [ [ MessageProperty [ Type=STRING Name=routingId Value="abcd-efgh-ijkl" ] ][ MessageProperty [ Type=INT64 Name=timestamp Value=123456789 ] ] ] ] ]
```

### Describe the solution you'd like

Implement `toString` for `PutMessageAdapter` and `AckMessageAdapter

**Comment by 678098** [comment]
Hi @sindhunaydu 
Thanks for your interest!

**Comment by sindhunaydu** [comment]
Hi @678098, I created a PR. While trying to setup the project locally I ran into couple of issues,

1. when I ran the `$ mvn clean install` command, I'm getting the following error - 
```[INFO] --- exec:3.0.0:exec (build-docker-image) @ bmq-sdk ---
No docker image was provided
Script usage:
	docker-build.sh image_name
	BMQ_DOCKER_IMAGE=image_name docker-build.sh
[ERROR] Command execution failed.
org.apache.commons.exec.ExecuteException: Process exited with an error: 1 (Exit value: 1)
```
In the readme file Docker was not mentioned, not sure what I am missing here.

2. In the [Building BlazingMQ Backend](https://github.com/bloomberg/blazingmq-sdk-java#building-blazingmq-backend) section, the link to setting up backed seems to be broken, its returning a 404 (https://github.com/bloomberg/blazingmq-sdk-java/blob/main/www.github.com/bloomberg/blazingmq)

**Comment by 678098** [comment]
@sindhunaydu thank you for the feedback,
1. This problem is related to integration tests run. We use docker image with `bmqbrkr` here to test SDK.
We will make this process smooth once we have docker image published in a public registry.
For now it's easier to use other mvn commands, to build: `mvn clean compile` to run UTs: `mvn -B -q -Dspotbugs.skip=true -Dspotless.check.skip=true test`
2. Updated broken link here: https://github.com/bloomberg/blazingmq-sdk-java/pull/17

**Comment by sindhunaydu** [comment]
Thanks for the fix @678098. and yes, this command works - `mvn -B -q -Dspotbugs.skip=true -Dspotless.check.skip=true test`.

**Comment by 678098** [comment]
Fixed: https://github.com/bloomberg/blazingmq-sdk-java/pull/16
